name: Send a Discord message when new RSS feeds update
on:
  rss:
    url: https://www.reddit.com/r/migraine/rising.rss
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_REDDIT_RISING }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_REDDIT }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_REDDIT }}
        uses: Ilshidur/action-discord@master
        with:
          args: "'`'headache - Reddit - Rising by. ${{on.rss.outputs.author}}'`''\n'**${{on.rss.outputs.title}}**'\n'${{on.rss.outputs.link}}"
