name: Send a Discord message when new RSs feeds update
on:
  rss:
    url: https://www.reddit.com/r/headache/hot.rss
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Escape Quotes
        id: escape
        run: |
          title="${{on.reddit.outputs.title}}"
          escaped_title=$(echo "$title" | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
          echo "::set-output name=escaped_title::$escaped_title"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_REDDIT_HOT }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_REDDIT }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_REDDIT }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`Headache - Reddit - Hot by. ${{on.rss.outputs.author}} 🔥`'\n'**${{steps.escape.outputs.escaped_title}}**'\n'${{on.rss.outputs.link}}"
